### ISSUE TITLE
firebaseならs3じゃなくfirebase hostringになる方が嬉しいのでは…

### ISSUE THREAD

**Issue by aHisayoshiSuehiro** [jacoyutorius/nuxt_firebase_kpt#2]
GJです
awsとfirebase両方必要だと若干セットアップが面倒な気持ちになったので
firebaseのhostingに乗せるとかどうでしょう…？

**Comment by jacoyutorius** [comment]
どもです。
確かにFirebaseのほうが良さそうですね。連休中にトライしてみます ✋

**Comment by aHisayoshiSuehiro** [comment]
期待してます！

**Comment by jacoyutorius** [comment]
Firebase Hostingでホストする場合の設定ファイルを追記しました。
FIrebaseCLIで"firebase deploy"してあげればいけると思いますが、足りない点あればまたご指摘ください ✋ 

66f0e1cad46c3d33ec6d728ce46bafa7e7b8d22f
